_target_: sv2m.models.made.MaDE

video_encoder:
  _target_: sv2m.models.made.UnimodalEncoder
  projector:
    _target_: torch.nn.Linear
    in_features: 512
    out_features: 256
  activation: false
  temporal_backbone:
    _target_: sv2m.modules.transformer.SelfAttentionTransformer
    positional_encoding:
      _target_: sv2m.modules.positional_encoding.PositionalEncoding
      seq_len: 250
      dim_model: ${...projector.out_features}
    dim_in: ${..projector.out_features}
    depth: 1
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dim_out: ${..projector.out_features}
    dropout: 0.8
    use_cls_token: false

music_encoder:
  _target_: sv2m.models.made.UnimodalEncoder
  projector:
    _target_: torch.nn.Linear
    in_features: 768
    out_features: 256
  activation: false
  temporal_backbone:
    _target_: sv2m.modules.transformer.SelfAttentionTransformer
    positional_encoding:
      _target_: sv2m.modules.positional_encoding.PositionalEncoding
      seq_len: 300
      dim_model: ${...projector.out_features}
    dim_in: ${..projector.out_features}
    depth: 1
    heads: 8
    dim_head: 64
    mlp_dim: 1024
    dim_out: ${..projector.out_features}
    dropout: 0.8
    use_cls_token: false


loss_fn:
  _target_: sv2m.criterion.CrossModalInfoNCELoss
  video_aggregators:
    - _target_: sv2m.modules.aggregater.AverageAggregator
      insert_cls_token: false
      insert_dist_token: false
      use_span_mask: false 
    - _target_: sv2m.modules.aggregater.AverageAggregator
      insert_cls_token: false
      insert_dist_token: false
      use_span_mask: false   
  music_aggregators:
    - _target_: sv2m.modules.aggregater.AverageAggregator
      insert_cls_token: false
      insert_dist_token: false
      use_span_mask: false  
    - _target_: sv2m.modules.aggregater.XPoolAggregator
      insert_cls_token: false
      insert_dist_token: false
      dim_input: ${....music_encoder.projector.out_features}
      num_heads: 1
      dropout: 0.3
      use_span_mask: false
  temperature: 0.09
  min_temperature: 0.07
  delete_duplicate: true
  distribution_loss: null
    