trainer:
  _target_:

seed: 0

torch_dtype:

ddp_kwargs:

output:
  exp_dir: "exp/"
  tensorboard_dir: "tensorboard/"
  model:
    epoch:
      path: ${...exp_dir}/model/epoch{epoch}.pth
      every: 1
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth
    last_epoch:
      path: ${...exp_dir}/model/last_epoch.pth

steps:
  epochs:
  iterations:

checkpoint:
  resume_from: