defaults:
  - default
  - _self_

trainer:
  _target_: sv2m.utils.driver.MaDETrainer.build_from_config

ddp_kwargs:
  find_unused_parameters: false

output:
  model:
    epoch:
      every: 1

steps:
  epochs: 100