defaults:
  - default
  - _self_

trainer:
  _target_: musreel.utils.driver.MVPtTrainer.build_from_config

ddp_kwargs:
  find_unused_parameters: false

output:
  model:
    epoch:
      every: 50

steps:
  epochs: 200